# fault_scenarios.py
# Exam build scenario table. Keep only hidden injection parameters here.
# Do not store answer-like metadata in this file.

from domain.constants import E04_PT3_RATIO

SCENARIOS: dict = {'': {'params': {}},
 'E01': {'params': {'pt1_phase_order': ['B', 'A', 'C'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C']}},
 'E02': {'params': {'pt3_phase_order': ['A', 'C', 'B'],
                    'g2_loop_swap': ('B', 'C'),
                    'g2_blackbox_order': ['A', 'C', 'B']}},
 'E03': {'params': {'pt3_a_reversed': True}},
 'E04': {'params': {'pt3_ratio': E04_PT3_RATIO}},
 'E05': {'params': {'pt1_phase_order': ['B', 'A', 'C'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['B', 'A', 'C'],
                    'pt1_sec_blackbox_order': ['B', 'A', 'C']}},
 'E06': {'params': {'pt1_phase_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['B', 'A', 'C'],
                    'pt1_sec_blackbox_order': ['A', 'B', 'C']}},
 'E07': {'params': {'pt1_phase_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['A', 'B', 'C'],
                    'pt1_sec_blackbox_order': ['B', 'A', 'C']}},
 'E08': {'params': {'pt1_phase_order': ['A', 'B', 'C'],
                    'pt1_pri_blackbox_order': ['B', 'A', 'C'],
                    'pt1_sec_blackbox_order': ['B', 'A', 'C']}},
 'E09': {'params': {'pt1_phase_order': ['A', 'B', 'C'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['A', 'B', 'C'],
                    'pt1_sec_blackbox_order': ['B', 'A', 'C']}},
 'E10': {'params': {'pt1_phase_order': ['A', 'B', 'C'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['B', 'A', 'C'],
                    'pt1_sec_blackbox_order': ['A', 'B', 'C']}},
 'E11': {'params': {'pt1_phase_order': ['B', 'C', 'A'],
                    'pt1_pri_blackbox_order': ['B', 'A', 'C'],
                    'pt1_sec_blackbox_order': ['A', 'C', 'B']}},
 'E12': {'params': {'pt1_phase_order': ['B', 'C', 'A'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['A', 'B', 'C'],
                    'pt1_sec_blackbox_order': ['A', 'C', 'B']}},
 'E13': {'params': {'pt1_phase_order': ['B', 'C', 'A'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['A', 'C', 'B'],
                    'pt1_sec_blackbox_order': ['A', 'B', 'C']}},
 'E14': {'params': {'pt1_phase_order': ['A', 'B', 'C'],
                    'g1_loop_swap': ('A', 'B'),
                    'g1_blackbox_order': ['B', 'A', 'C'],
                    'pt1_pri_blackbox_order': ['A', 'C', 'B'],
                    'pt1_sec_blackbox_order': ['C', 'A', 'B']}},
 'E17': {'params': {'pt2_sec_blackbox_order': ['A', 'C', 'B']}},
 'E18': {'params': {'pt2_sec_blackbox_order': ['B', 'A', 'C']}},
 'E19': {'params': {'pt2_sec_blackbox_order': ['C', 'B', 'A']}},
 'E20': {'params': {'pt2_sec_blackbox_order': ['B', 'C', 'A']}},
 'E21': {'params': {'pt2_sec_blackbox_order': ['C', 'A', 'B']}}}
